### PR TITLE
Fix machine_info hooks.

### PR DESCRIPTION
**Pull request by asford**
Resolves issue with `pytest_benchmark_update_machine_info`
hooks not being executed, as cached `machine_info` property is retrieved
(and cached) during benchmark plugin initialization *before*
user-defined `conftest.py` modules are loaded.

Convert machine info from cached property to explicit generation
function, and generate once per `handle_saving`/`handle_loading` call.

The error can be reproduced by adding a trivial hook to a project `conftest.py`:

```python
def pytest_benchmark_update_machine_info(config, machine_info):
    raise NotImplementedError
```

This *should* fail with a `NotImplementedError`, but the hook is never called.

Running under:

```
pytest==3.5.1
pytest-benchmark==3.1.1
pytest-cov==2.5.1
pytest-faulthandler==1.5.0
pytest-forked==0.2
pytest-instafail==0.4.0
pytest-watch==4.2.0
pytest-xdist==1.22.2
```

### CODE REVIEW

**Comment by ionelmc** [comment]
I would like to have a test for this situation as well - the bug is way too weird to not have one.

**Comment by asford** [comment]
Yes, I agree. It's a bit tough to test in the current regime, as it relies on the integration between pytest's plugin load infrastructure and the session object. I've had a *some* trouble determining how to isolate out this component within the unit test infrastructure and get a repro case.

Would you be ok with an end-to-end integrated reproduction case? This might involve reinvoking pytest in a manner similar to the current `test_cli.py` test cases.

**Comment by asford** [comment]
To expand above, that isn't to say it isn't possible to get a more isolated repoduction. I've relatively little experience working with pytest plugins, and would be happy to have guidance if there's a better testing strategy.

**Comment by ionelmc** [comment]
For example test take a look at https://github.com/ionelmc/pytest-benchmark/blob/master/tests/test_benchmark.py#L232 (eg `testdir.makepyfile(conftest='....')`)

**Comment by asford** [comment]
Great, thanks for the ref. I was unaware of the `pytester` component.

I've added a repro case and rebased the fix over that test so the error can be verified via the intermediate commit.

**Comment by ionelmc** [comment]
So after some debugging it appears the actual problem is that pytest will try to peek into all attributes of a fixture for some reason, eg:
```py
        for name in dir(holderobj):
            # The attribute can be an arbitrary descriptor, so the attribute
            # access below can raise. safe_getatt() ignores such exceptions.
            obj = safe_getattr(holderobj, name, None)
```

So it's unsafe to have any properties on a fixture. Huh.

**Pull request merged**
