### PR TITLE
Add Python 3.9, drop Python 3.5

### PR DESCRIPTION
**Pull request by eumiro**
Add Python 3.9 support to tox, Travis, and Appveyor.

Any plans for dropping 2.7 and/or 3.5 support?

### CODE REVIEW

**Comment by ionelmc** [comment]
No plans yet to drop 2.7, but we can drop 3.5 right now (upgrading 3.5 to 3.6 should be a breeze).

**Comment by eumiro** [comment]
Dropping 3.5 was a breeze, adding 3.9 shows some problems in `.appveyor.yml` because of differently supported Python versions, so I'll have to see what it does.

Dropping 2.7 will make the code more beautiful. :innocent:

**Comment by eumiro** [comment]
Oh right, Python 3.9 needs the new version of Visual Studio: https://www.appveyor.com/docs/windows-images-software/#python

**Comment by eumiro** [comment]
6 hours later and it is still not over? How about moving to GitHub Actions?

**Comment by ionelmc** [comment]
It's due for a move to travis-ci.com (travis-ci.org is practically dead now). I got all the necessary changes in cookiecutter-pylibrary...

**Pull request merged**
